'use strict';

const http = require('http');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const PORT = Number(process.env.PORT || 3000);
const HOST = '0.0.0.0';
const BASE = '/ltt/v1';
const DATA_DIR = process.env.DATA_DIR || '/app/data';
const SOCIAL_FILE = path.join(DATA_DIR, 'ltt-social.json');
const MAX_BODY = 1024 * 1024;
const MAX_SCHEMATIC = 48 * 1024 * 1024;
const SESSION_TTL = 5 * 60 * 1000;
const ROOM_CODE_ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
const USER_RE = /^[A-Za-z0-9_]{3,16}$/;

const clients = new Map();
const onlineByName = new Map();
const rooms = new Map();
const profileCache = new Map();
let social = loadSocial();

function b64(value) { return Buffer.from(String(value == null ? '' : value), 'utf8').toString('base64url'); }
function unb64(value) { try { return Buffer.from(String(value || ''), 'base64url').toString('utf8'); } catch { return ''; } }
function line(type, ...fields) { return [type, ...fields.map(b64)].join('\t'); }
function parseLine(raw) { const parts = String(raw || '').trim().split('\t'); return { type: parts[0] || '', fields: parts.slice(1).map(unb64) }; }
function sendText(res, status, text) { const body = Buffer.from(String(text || ''), 'utf8'); res.writeHead(status, {'content-type':'text/plain; charset=utf-8','content-length':body.length,'cache-control':'no-store','access-control-allow-origin':'*'}); res.end(body); }
function readBody(req, max = MAX_BODY) { return new Promise((resolve, reject) => { const chunks=[]; let total=0; req.on('data', chunk => { total += chunk.length; if (total > max) { reject(Object.assign(new Error('body too large'), {statusCode:413})); req.destroy(); return; } chunks.push(chunk); }); req.on('end',()=>resolve(Buffer.concat(chunks))); req.on('error',reject); }); }
function now(){return Date.now();} function lower(name){return String(name||'').trim().toLowerCase();} function validUser(name){return USER_RE.test(String(name||'').trim());} function randomToken(bytes=24){return crypto.randomBytes(bytes).toString('base64url');}
function roomCode(){for(let tries=0;tries<20;tries++){let code='';const bytes=crypto.randomBytes(8);for(let i=0;i<8;i++)code+=ROOM_CODE_ALPHABET[bytes[i]%ROOM_CODE_ALPHABET.length];if(!rooms.has(code))return code;}throw new Error('could not allocate room code');}
function getUser(name,create=true){const key=lower(name);if(!key)return null;if(!social.users[key]&&create)social.users[key]={name:String(name).trim(),uuid:'',friends:[],incoming:[],outgoing:[]};return social.users[key]||null;}
function uniqueLower(list){return[...new Set((list||[]).map(lower).filter(Boolean))];} function ensureUserShape(user){if(!user)return;user.friends=uniqueLower(user.friends);user.incoming=uniqueLower(user.incoming);user.outgoing=uniqueLower(user.outgoing);}
function loadSocial(){try{const data=JSON.parse(fs.readFileSync(SOCIAL_FILE,'utf8'));if(!data||typeof data!=='object')throw new Error('bad data');data.users||={};for(const user of Object.values(data.users))ensureUserShape(user);return data;}catch{return{users:{}};}}
function saveSocial(){try{fs.mkdirSync(DATA_DIR,{recursive:true});const tmp=SOCIAL_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(social,null,2),'utf8');fs.renameSync(tmp,SOCIAL_FILE);}catch(error){console.error('[LTT SERVICE] social save failed',error);}}
function queue(session,eventLine){if(!session||!eventLine)return;session.events.push(eventLine);if(session.events.length>256)session.events.splice(0,session.events.length-256);flushPoll(session);}
function flushPoll(session){if(!session.pendingPoll||session.events.length===0)return;const pending=session.pendingPoll;session.pendingPoll=null;clearTimeout(pending.timer);sendText(pending.res,200,session.events.splice(0,64).join('\n'));}
function sessionFor(token){const s=clients.get(String(token||''));if(!s)return null;s.lastSeen=now();return s;} function onlineSession(name){const token=onlineByName.get(lower(name));return token?clients.get(token)||null:null;} function userIsFriend(a,b){const ua=getUser(a,false);return!!ua&&ua.friends.includes(lower(b));} function roomOf(session){return session&&session.roomCode?rooms.get(session.roomCode)||null:null;}
function broadcast(room,eventLine,exceptToken=null){if(!room)return;for(const token of room.members){if(token===exceptToken)continue;queue(clients.get(token),eventLine);}}
function broadcastMembers(room){if(!room)return;const names=[...room.members].map(t=>clients.get(t)?.name).filter(Boolean);broadcast(room,line('MEMBERS',...names));}
function closeRoom(room,reason='Room closed'){if(!room||!rooms.delete(room.code))return;for(const token of[...room.members]){const s=clients.get(token);if(s){s.roomCode='';if(token!==room.hostToken)queue(s,line('ROOM_CLOSED',reason));}}notifyPresenceForRoom(room);}
function leaveRoom(session,disconnected=false){const room=roomOf(session);if(!room){session.roomCode='';return;}if(room.hostToken===session.token){closeRoom(room,disconnected?'Room host disconnected':'Room closed by host');return;}room.members.delete(session.token);session.roomCode='';broadcastMembers(room);notifyPresenceForUser(session.name);}
function notifyPresenceForUser(name){const user=getUser(name,false);if(!user)return;for(const friendKey of user.friends){const friend=social.users[friendKey];const s=friend?onlineSession(friend.name):null;if(s)sendFriendsSnapshot(s);}const self=onlineSession(name);if(self)sendFriendsSnapshot(self);}
function notifyPresenceForRoom(room){if(!room)return;for(const token of room.members){const s=clients.get(token);if(s)notifyPresenceForUser(s.name);}}
function sendPending(session){const user=getUser(session.name);ensureUserShape(user);queue(session,line('FRIEND_INCOMING_LIST',...user.incoming.map(k=>social.users[k]?.name||k)));queue(session,line('FRIEND_OUTGOING_LIST',...user.outgoing.map(k=>social.users[k]?.name||k)));}
function sendFriendsSnapshot(session){const user=getUser(session.name);ensureUserShape(user);queue(session,line('FRIENDS_BEGIN',String(user.friends.length)));for(const friendKey of user.friends){const record=social.users[friendKey];const display=record?.name||friendKey;const peer=onlineSession(display);const room=peer?roomOf(peer):null;const peerIsHost=!!room&&room.hostToken===peer.token;queue(session,line('FRIEND_STATE',display,peer?'1':'0',peer?.serverAddress||'',peer?.serverFingerprint||'',peerIsHost?room.code:''));}queue(session,line('FRIENDS_END'));}
async function lookupProfile(name){const key=lower(name),cached=profileCache.get(key);if(cached&&now()-cached.at<600000)return cached.value;try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),3500);const response=await fetch(`https://api.minecraftservices.com/minecraft/profile/lookup/name/${encodeURIComponent(name)}`,{headers:{accept:'application/json','user-agent':'LitematicaTogether/0.6'},signal:controller.signal});clearTimeout(timer);if(response.status===404||response.status===204){profileCache.set(key,{at:now(),value:null});return null;}if(!response.ok)throw new Error(`lookup ${response.status}`);const json=await response.json();const value=json&&validUser(json.name)?{name:json.name,uuid:String(json.id||'')}:null;profileCache.set(key,{at:now(),value});return value;}catch{return{name:String(name).trim(),uuid:''};}}
function parseAction(body){const msg=parseLine(body.toString('utf8'));if(msg.type!=='ACTION'||msg.fields.length<2)return null;const[token,action,...args]=msg.fields;return{token,action,args};}
function requireSession(res,token){const session=sessionFor(token);if(!session)sendText(res,401,line('ERR','session','Session expired. Reconnect to Litematica Together service.'));return session;} function ok(res,...fields){sendText(res,200,line('OK',...fields));} function err(res,code,message,status=400){sendText(res,status,line('ERR',code,message));}
async function handleHello(req,res){const body=await readBody(req),msg=parseLine(body.toString('utf8'));if(msg.type!=='HELLO'||msg.fields.length<5)return err(res,'protocol','Invalid HELLO');let[name,uuid,serverFingerprint,serverAddress,version]=msg.fields;name=String(name||'').trim();if(!validUser(name))return err(res,'username','Invalid Minecraft username');const key=lower(name),oldToken=onlineByName.get(key);if(oldToken)disconnectSession(clients.get(oldToken),'Signed in from another client');const user=getUser(name);user.name=name;if(uuid)user.uuid=uuid;ensureUserShape(user);saveSocial();const token=randomToken();const session={token,name,uuid:String(uuid||''),version:String(version||''),serverFingerprint:String(serverFingerprint||''),serverAddress:String(serverAddress||''),roomCode:'',events:[],pendingPoll:null,lastSeen:now(),rate:{at:now(),count:0}};clients.set(token,session);onlineByName.set(key,token);ok(res,token);sendPending(session);sendFriendsSnapshot(session);notifyPresenceForUser(name);}
function rateAllowed(session,limit=40){const t=now();if(t-session.rate.at>=1000){session.rate.at=t;session.rate.count=0;}session.rate.count++;return session.rate.count<=limit;}
async function handleAction(req,res){const body=await readBody(req),parsed=parseAction(body);if(!parsed)return err(res,'protocol','Invalid action');const session=requireSession(res,parsed.token);if(!session)return;if(!rateAllowed(session))return err(res,'rate','Too many requests',429);const a=parsed.action,args=parsed.args;
if(a==='PRESENCE'){const[fp='',address='']=args,changed=session.serverFingerprint!==fp||session.serverAddress!==address;session.serverFingerprint=fp;session.serverAddress=address;if(changed)notifyPresenceForUser(session.name);return ok(res);}
if(a==='ROOM_CREATE'){if(!session.serverFingerprint||!session.serverAddress)return err(res,'server','Join a multiplayer server first');if(roomOf(session))return err(res,'room','Already in a room');const code=roomCode(),room={code,hostToken:session.token,serverFingerprint:session.serverFingerprint,serverAddress:session.serverAddress,permission:'INVITE_ONLY',members:new Set([session.token]),schematic:null,schematicVersion:0,placement:null,createdAt:now()};rooms.set(code,room);session.roomCode=code;ok(res,code);broadcastMembers(room);notifyPresenceForUser(session.name);return;}
if(a==='ROOM_JOIN'){const code=String(args[0]||'').trim().toUpperCase(),room=rooms.get(code);if(!room)return err(res,'not_found','Room code does not exist or has expired');if(!session.serverFingerprint||session.serverFingerprint!==room.serverFingerprint)return err(res,'different_server','You must be on the same Minecraft server as the room host');if(roomOf(session)&&session.roomCode!==code)leaveRoom(session);if(room.permission==='FRIENDS'){const host=clients.get(room.hostToken);if(!host||!userIsFriend(host.name,session.name))return err(res,'friends_only','This room is friends only');}room.members.add(session.token);session.roomCode=code;const host=clients.get(room.hostToken);ok(res,code,host?.name||'Host');broadcastMembers(room);if(room.placement)queue(session,line('PLACEMENT',String(room.placement.x),String(room.placement.y),String(room.placement.z),room.placement.rotation,room.placement.mirror));if(room.schematic)queue(session,line('SCHEMATIC',code,String(room.schematicVersion),room.schematic.name,String(room.schematic.size)));notifyPresenceForUser(session.name);return;}
if(a==='ROOM_LEAVE'){leaveRoom(session);return ok(res);} if(a==='ROOM_PERMISSION'){const room=roomOf(session);if(!room||room.hostToken!==session.token)return err(res,'leader','Only the room leader can change permissions');const mode=args[0]==='FRIENDS'?'FRIENDS':'INVITE_ONLY';room.permission=mode;broadcast(room,line('PERMISSION',mode));return ok(res,mode);}
if(a==='PLACEMENT'){const room=roomOf(session);if(!room)return err(res,'room','Not in a room');const[xs,ys,zs,rotation='NONE',mirror='NONE']=args,x=Number(xs),y=Number(ys),z=Number(zs);if(![x,y,z].every(Number.isInteger))return err(res,'placement','Invalid placement');room.placement={x,y,z,rotation,mirror};broadcast(room,line('PLACEMENT',String(x),String(y),String(z),rotation,mirror),session.token);return ok(res);}
if(a==='FRIENDS_REFRESH'){sendPending(session);sendFriendsSnapshot(session);return ok(res);} if(a==='FRIEND_REQUEST'){const requested=String(args[0]||'').trim();if(!validUser(requested))return err(res,'username','Minecraft names must be 3-16 letters, numbers or _');if(lower(requested)===lower(session.name))return err(res,'self','You cannot add yourself');const profile=await lookupProfile(requested);if(!profile)return err(res,'not_found','That Minecraft username does not exist');const target=getUser(profile.name);target.name=profile.name;if(profile.uuid)target.uuid=profile.uuid;const me=getUser(session.name),tk=lower(target.name),mk=lower(me.name);ensureUserShape(me);ensureUserShape(target);if(me.friends.includes(tk))return err(res,'exists',`${target.name} is already your friend`);if(!me.outgoing.includes(tk))me.outgoing.push(tk);if(!target.incoming.includes(mk))target.incoming.push(mk);saveSocial();ok(res,target.name);const targetSession=onlineSession(target.name);if(targetSession){queue(targetSession,line('FRIEND_REQUEST',session.name));sendPending(targetSession);}sendPending(session);return;}
if(a==='FRIEND_RESPONSE'){const fromName=String(args[0]||'').trim(),accept=args[1]==='1',me=getUser(session.name),from=getUser(fromName,false);if(!from)return err(res,'request','Friend request no longer exists');const mk=lower(me.name),fk=lower(from.name);ensureUserShape(me);ensureUserShape(from);if(!me.incoming.includes(fk))return err(res,'request','Friend request no longer exists');me.incoming=me.incoming.filter(x=>x!==fk);from.outgoing=from.outgoing.filter(x=>x!==mk);if(accept){if(!me.friends.includes(fk))me.friends.push(fk);if(!from.friends.includes(mk))from.friends.push(mk);}saveSocial();ok(res,from.name,accept?'1':'0');const fromSession=onlineSession(from.name);if(fromSession){queue(fromSession,line('FRIEND_RESPONSE',session.name,accept?'1':'0'));sendPending(fromSession);sendFriendsSnapshot(fromSession);}sendPending(session);sendFriendsSnapshot(session);return;}
if(a==='FRIEND_REMOVE'){const targetName=String(args[0]||'').trim(),me=getUser(session.name),target=getUser(targetName,false);if(!target)return err(res,'friend','Friend not found');const mk=lower(me.name),tk=lower(target.name);me.friends=me.friends.filter(x=>x!==tk);target.friends=target.friends.filter(x=>x!==mk);saveSocial();ok(res);sendFriendsSnapshot(session);const targetSession=onlineSession(target.name);if(targetSession)sendFriendsSnapshot(targetSession);return;}
if(a==='ROOM_INVITE'){const targetName=String(args[0]||'').trim(),room=roomOf(session);if(!room||room.hostToken!==session.token)return err(res,'leader','Only the room leader can invite friends');if(!userIsFriend(session.name,targetName))return err(res,'friend','That player is not in your Friends list');const target=onlineSession(targetName);if(!target)return err(res,'offline',`${targetName} is offline`);queue(target,line('ROOM_INVITE',session.name,room.code,room.serverAddress,room.serverFingerprint));return ok(res,target.name);}
if(a==='FRIEND_JOIN'){const targetName=String(args[0]||'').trim();if(!userIsFriend(session.name,targetName))return err(res,'friend','That player is not in your Friends list');const target=onlineSession(targetName);if(!target)return err(res,'offline',`${targetName} is offline`);const room=roomOf(target),roomCode=room&&room.hostToken===target.token?room.code:'';return ok(res,target.serverAddress||'',target.serverFingerprint||'',roomCode);}
return err(res,'action','Unknown action');}
async function handlePoll(req,res,url){const session=requireSession(res,url.searchParams.get('token'));if(!session)return;if(session.events.length)return sendText(res,200,session.events.splice(0,64).join('\n'));if(session.pendingPoll){clearTimeout(session.pendingPoll.timer);sendText(session.pendingPoll.res,204,'');}const timer=setTimeout(()=>{if(session.pendingPoll?.res===res)session.pendingPoll=null;if(!res.writableEnded)sendText(res,204,'');},20000);session.pendingPoll={res,timer};req.on('close',()=>{if(session.pendingPoll?.res===res){clearTimeout(timer);session.pendingPoll=null;}});}
async function handleSchematicUpload(req,res,url){const session=requireSession(res,url.searchParams.get('token'));if(!session)return;const room=roomOf(session);if(!room||room.hostToken!==session.token)return err(res,'leader','Only the room leader can share the schematic');const body=await readBody(req,MAX_SCHEMATIC);if(!body.length)return err(res,'schematic','Empty schematic');const name=unb64(req.headers['x-ltt-name']||'')||'shared.litematic',x=Number(req.headers['x-ltt-x']||0),y=Number(req.headers['x-ltt-y']||0),z=Number(req.headers['x-ltt-z']||0),rotation=unb64(req.headers['x-ltt-rotation']||'')||'NONE',mirror=unb64(req.headers['x-ltt-mirror']||'')||'NONE';room.schematicVersion++;room.schematic={name:path.basename(name).slice(0,180),bytes:body,size:body.length};room.placement={x,y,z,rotation,mirror};ok(res,String(room.schematicVersion));broadcast(room,line('SCHEMATIC',room.code,String(room.schematicVersion),room.schematic.name,String(body.length)),session.token);broadcast(room,line('PLACEMENT',String(x),String(y),String(z),rotation,mirror),session.token);}
async function handleSchematicDownload(req,res,url){const session=requireSession(res,url.searchParams.get('token'));if(!session)return;const room=roomOf(session);if(!room||!room.schematic)return err(res,'schematic','No shared schematic',404);const wanted=Number(url.searchParams.get('version')||room.schematicVersion);if(wanted!==room.schematicVersion)return err(res,'schematic','Schematic version expired',409);const s=room.schematic;res.writeHead(200,{'content-type':'application/octet-stream','content-length':s.bytes.length,'cache-control':'no-store','x-ltt-name':b64(s.name),'x-ltt-x':String(room.placement?.x||0),'x-ltt-y':String(room.placement?.y||0),'x-ltt-z':String(room.placement?.z||0),'x-ltt-rotation':b64(room.placement?.rotation||'NONE'),'x-ltt-mirror':b64(room.placement?.mirror||'NONE')});res.end(s.bytes);}
function disconnectSession(session,reason='Disconnected'){if(!session||!clients.has(session.token))return;clients.delete(session.token);if(onlineByName.get(lower(session.name))===session.token)onlineByName.delete(lower(session.name));if(session.pendingPoll){clearTimeout(session.pendingPoll.timer);if(!session.pendingPoll.res.writableEnded)sendText(session.pendingPoll.res,401,line('ERR','session',reason));}leaveRoom(session,true);notifyPresenceForUser(session.name);}
function cleanup(){const cutoff=now()-SESSION_TTL;for(const session of clients.values())if(session.lastSeen<cutoff)disconnectSession(session,'Session timed out');for(const room of rooms.values())if(!clients.has(room.hostToken))closeRoom(room,'Room host disconnected');} setInterval(cleanup,60000).unref();
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'*'});return res.end();}if(req.method==='GET'&&(url.pathname==='/'||url.pathname===`${BASE}/health`))return sendText(res,200,line('HEALTH','ok',String(clients.size),String(rooms.size)));if(req.method==='POST'&&url.pathname===`${BASE}/hello`)return await handleHello(req,res);if(req.method==='POST'&&url.pathname===`${BASE}/action`)return await handleAction(req,res);if(req.method==='GET'&&url.pathname===`${BASE}/poll`)return await handlePoll(req,res,url);if(req.method==='POST'&&url.pathname===`${BASE}/schematic`)return await handleSchematicUpload(req,res,url);if(req.method==='GET'&&url.pathname===`${BASE}/schematic`)return await handleSchematicDownload(req,res,url);return sendText(res,404,line('ERR','not_found','Not found'));}catch(error){if(!res.writableEnded)sendText(res,error.statusCode||500,line('ERR','server',error.message||'Internal error'));console.error('[LTT SERVICE]',error);}});
server.listen(PORT,HOST,()=>console.log(`[LTT SERVICE] listening on ${HOST}:${PORT}${BASE}`));
module.exports={server,BASE};
